default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: barpay_api_development
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: test

test:
  <<: *default
  database: barpay_api_test
  port: 5432
  user: postgres
  password: test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
